//ANNOUNCEMENT
export const MAX_LENGTH_ANNOUNCEMENT_TITLE = 256;
export const MIN_LENGTH_ANNOUNCEMENT_TITLE = 3;
export const MAX_LENGTH_ANNOUNCEMENT_CONTENT = 5096;
export const MIN_LENGTH_ANNOUNCEMENT_CONTENT = 3;
export const MAX_LENGHT_ANNOUNCEMENT_RESPONSIBLE = 256;
export const MIN_LENGHT_ANNOUNCEMENT_RESPONSIBLE = 3;
